Vagrant.configure("2") do |config|
  config.vm.box = "aspyatkin/ubuntu-18.04-server"
  
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.name = "ubuntu-dev-01"
    v.linked_clone = true

    v.check_guest_additions = true
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
    end

    v.memory = 2048
    v.cpus = 1
  end
end
