Vagrant.configure("2") do |config|
  config.vm.box = "aspyatkin/ubuntu-18.04-server"
  
  config.vm.hostname = "ubuntu-dev-03"
  config.vm.network "private_network", type: "dhcp"
  
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.name = "ubuntu-dev-03"
    v.linked_clone = true

    v.check_guest_additions = true
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
    end

    v.memory = 2048
    v.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y vim
  SHELL
end
