version: "3.8"

services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    networks:
      - my-network
    ports:
      - 80:80

  requester:
    build:
      context: ./requester/
      dockerfile: Dockerfile
    networks:
      - my-network
    

networks:
  my-network:
    # Use a custom driver
    driver: bridge