Vagrant.configure("2") do |config|
  config.vm.box = "aspyatkin/ubuntu-18.04-server"
  
  config.vm.network "private_network", type: "dhcp"
  
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.linked_clone = true

    v.check_guest_additions = true
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
    end

    v.memory = 2048
    v.cpus = 1
  end

  config.vm.provision "shell", path: "./install_packages.sh"

  config.vm.define "host1", primary: true do |host|
    host.vm.hostname = "host1"
    host.vm.network "private_network", ip: "192.168.100.10"
    host.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  end

  config.vm.define "host2" do |host|
    host.vm.hostname = "host2"
    host.vm.network "private_network", ip: "192.168.100.11"
  end 

  config.vm.define "host3" do |host|
    host.vm.hostname = "host3"
    host.vm.network "private_network", ip: "192.168.100.12"
    config.vm.provision "shell", path: "./install_dnsutils.sh"
  end 
end
