Vagrant.configure("2") do |config|
  config.vm.box = "aspyatkin/ubuntu-18.04-server"
  
  config.vm.hostname = "ubuntu-dev-04"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.name = "ubuntu-dev-04"
    v.linked_clone = true

    v.check_guest_additions = true
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
    end

    v.memory = 2048
    v.cpus = 1
  end


  config.vm.provision "file", source: "./AWS-Aicor-CodeCommit-ISADevOpsR1", destination: "~/.ssh/AWS-Aicor-CodeCommit-ISADevOpsR1"
  config.vm.provision "file", source: "./config", destination: "~/.ssh/config"
 # config.vm.provision "shell", inline: "chmod 400 ~/AWS-Aicor-CodeCommit-ISADevOpsR1"

  config.vm.provision "shell", path: "./install_packages.sh"
end
